project: SwiftOnMars.xcodeproj
retain_assign_only_properties: true
retain_unused_protocol_func_params: true
retain_objc_accessible: true
retain_public: true
external_encodable_protocols: true
schemes:
- SwiftOnMars
- SOMDataLayer
- SOMDomainLayer
targets:
- SwiftOnMars

verbose: false
skip_build: false
# strict: false
format: xcode 
